[package]
name = "elf-loader"
version = "0.1.0"
authors = ["zjuliangxun <m13009809900@163.com>"]
edition = "2018"

[dependencies]
goblin = { version = "0.4.2", default-features = false, features = ["elf32", "elf64", "endian_fd"] }
