[build]
target = "x86_64-unknown-none-elf.json"

[target.x86_64-unknown-none-elf]
runner = "x86-vmm-qemu"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
