[package]
name = "keystone-rt-runner"
version = "0.1.0"
edition = "2018"

[dependencies]
edge-responder = { path = "../edge-responder" }
hal = { path = "../hal", features = ["keystone"] }
nix = "0.22.0"
