[package]
name = "keystone-rt-runner"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1.0.1"
failure = "0.1.8"
keystone-cfg = { path = "../keystone-cfg" }
keystone-hal = { path = "../keystone-hal" }
nix = "0.20.0"
