[package]
name = "x86-vm-kernel"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.10.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
uart_16550 = "0.2.15"
x86_64 = "0.14.3"
