[package]
name = "keystone-hal"
version = "0.1.0"
edition = "2018"

[features]
rt = ["riscv"]

[dependencies]
edge-lib = { path = "../edge-lib", features = ["kernel"] }
riscv = { version = "0.6.0", features = ["inline-asm"], optional = true }
