[package]
name = "keystone-rt"
version = "0.1.0"
edition = "2018"

[dependencies]
keystone-cfg = { path = "../keystone-cfg" }
keystone-hal = { path = "../keystone-hal", features = ["rt"] }
log = "0.4.14"
riscv = { version = "0.6.0", features = ["inline-asm"] }

# enable no-std in phf
[dependencies.phf]
git = "https://github.com/Kazurin-775/rust-phf.git"
rev = "171f1f59"
default-features = false
features = ["macros"]
