[package]
name = "linux-abi"
version = "0.1.0"
edition = "2018"

[features]
keystone = ["hal/keystone-rt"]

[dependencies]
hal = { path = "../hal" }
log = "0.4.16"

# enable no-std in phf
[dependencies.phf]
version = "0.10.1"
default-features = false
features = ["macros"]
